 id: ggshield
  name: ggshield (pre-commit)
  entry: ggshield
  description: Runs ggshield to detect hardcoded secrets, security vulnerabilities and policy breaks.
  stages: [commit]
  args: ['secret', 'scan', 'pre-commit']
  language: python
  pass_filenames: false
